class_name AlleyCatExtraFont
extends RefCounted
## Draw the letters Alley Cat does not have, in the style of the ones it does.
##
## Generated by tools/make_font.py. Draw there, not here.

## The letters the game does not carry, in the order [method glyphs] returns them.
static func letters() -> String:
	return "BDFGJNOPQRWXYZ"


## One entry a letter, sixteen bytes each: two a row, four pixels a byte, ink where the letter is
## and the fence's own colour around it, which is what the game's own glyphs hold.
static func glyphs() -> Array[PackedByteArray]:
	var out: Array[PackedByteArray] = []
	out.append(PackedByteArray([0, 85, 5, 21, 5, 21, 0, 85, 65, 69, 65, 69, 64, 21, 85, 85]))  # B
	out.append(PackedByteArray([0, 85, 5, 21, 5, 69, 5, 69, 65, 81, 65, 69, 64, 21, 85, 85]))  # D
	out.append(PackedByteArray([0, 21, 5, 85, 5, 85, 0, 85, 65, 85, 65, 85, 65, 85, 85, 85]))  # F
	out.append(PackedByteArray([64, 21, 5, 85, 5, 85, 4, 5, 65, 65, 65, 65, 80, 5, 85, 85]))  # G
	out.append(PackedByteArray([80, 5, 85, 5, 85, 5, 85, 5, 65, 65, 65, 65, 80, 5, 85, 85]))  # J
	out.append(PackedByteArray([5, 69, 1, 69, 0, 69, 4, 5, 65, 65, 65, 81, 65, 81, 85, 85]))  # N
	out.append(PackedByteArray([64, 21, 5, 5, 5, 5, 5, 5, 65, 65, 65, 65, 80, 5, 85, 85]))  # O
	out.append(PackedByteArray([0, 85, 5, 21, 5, 21, 0, 85, 65, 85, 65, 85, 65, 85, 85, 85]))  # P
	out.append(PackedByteArray([64, 21, 5, 5, 5, 5, 5, 5, 65, 1, 65, 65, 80, 1, 85, 85]))  # Q
	out.append(PackedByteArray([0, 85, 5, 21, 5, 21, 0, 85, 65, 21, 65, 69, 65, 65, 85, 85]))  # R
	out.append(PackedByteArray([5, 5, 5, 5, 5, 5, 4, 5, 64, 1, 64, 65, 65, 65, 85, 85]))  # W
	out.append(PackedByteArray([5, 5, 64, 21, 80, 85, 80, 85, 80, 5, 65, 65, 65, 65, 85, 85]))  # X
	out.append(PackedByteArray([5, 5, 64, 21, 80, 85, 80, 85, 84, 21, 84, 21, 84, 21, 85, 85]))  # Y
	out.append(PackedByteArray([0, 5, 85, 5, 84, 21, 80, 85, 80, 85, 65, 85, 64, 1, 85, 85]))  # Z
	return out
